# Generated by Django 3.0.2 on 2020-02-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='file',
            field=models.FileField(blank='True', null='True', upload_to='files/'),
            preserve_default='True',
        ),
    ]
